version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 0:0
    network_mode: 'host'
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/xyzlocal:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://bt-joly2
    extra_hosts:
      - "host.docker.internal:host-gateway"
